# Generated by Django 3.2 on 2021-05-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authsignupstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthSignUpStudent',
        ),
    ]
